#!/usr/bin/env bash

set -euo pipefail

: "${REPO_DIR:?REPO_DIR must be exported}"
: "${APP_PORT:?APP_PORT must be exported}"
: "${DB_PASSWORD:?DB_PASSWORD must be exported}"

APP_DIR="/opt/mywebapp"
CONFIG_DIR="/etc/mywebapp"

echo "    -> deploying code to $APP_DIR"
mkdir -p "$APP_DIR" "$CONFIG_DIR"

if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$REPO_DIR/app/mywebapp/" "$APP_DIR/mywebapp/"
else
    rm -rf "$APP_DIR/mywebapp"
    cp -r "$REPO_DIR/app/mywebapp" "$APP_DIR/mywebapp"
fi
install -m 0644 "$REPO_DIR/app/migrate.py"        "$APP_DIR/migrate.py"
install -m 0644 "$REPO_DIR/app/requirements.txt"  "$APP_DIR/requirements.txt"

if [[ ! -d "$APP_DIR/venv" ]]; then
    echo "    -> creating venv with python3.12"
    python3.12 -m venv "$APP_DIR/venv"
fi
echo "    -> installing dependencies"
"$APP_DIR/venv/bin/pip" install --quiet --upgrade pip
"$APP_DIR/venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"

echo "    -> writing $CONFIG_DIR/env"
umask 027
cat > "$CONFIG_DIR/env" <<EOF
# Auto-generated by deploy/scripts/04-app.sh — do not edit by hand.
# This file feeds the systemd unit which then passes them as CLI args
# to the Python app (V2=1 → command-line argument configuration).
APP_HOST=127.0.0.1
APP_PORT=${APP_PORT}
DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=mywebapp
DB_USER=mywebapp
DB_PASSWORD=${DB_PASSWORD}
EOF
chown root:app "$CONFIG_DIR/env"
chmod 0640 "$CONFIG_DIR/env"

chown -R app:app "$APP_DIR"
chmod 0755 "$APP_DIR"

echo "    -> app installed under $APP_DIR (owner app:app)"
